services:
  # Streamlit Application
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501" # Expose Streamlit on port 8501
    volumes:
      - ./app:/app # Mount the app folder into the container
      - ./data:/data
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY} # Pass the Gemini API key as an environment variable
    depends_on:
      - duckdb # Ensure DuckDB is running before starting Streamlit

  # DuckDB Database Service
  duckdb:
    build:
      context: ./duckdb_service
      dockerfile: Dockerfile
    volumes:
      - ./data:/data # Persist DuckDB data in the host's `data/` directory
    environment:
      - DUCKDB_PATH=/data/invoices.db # Path to the DuckDB database file
    restart: on-failure